### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by darekkay** [darekkay/static-marks#11]
Prerequesites:

- [x] CSS colors should be refactored into CSS custom properties
- [x] SVGs have to be moved out of CSS (base64) into the markup to allow changing their colors. To keep the markup size small, the SVGs should probably be reused via `<use>` ([MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use)).

TODO:

- [x] Define dark theme, probably based on [this](https://github.com/darekkay/dashboard/blob/master/app/src/styles/themes/_dark.scss).
- [ ] Add theme switcher

All changes have to be done [in this repository](https://github.com/darekkay/static-marks-app/).

**Comment by sarveshh** [comment]
Hey @darekkay I would love to give this a try. Is that okay?

**Comment by darekkay** [comment]
Hey @sarveshh , sure, feel free :) But it might not be that simple given the not so up-to-date architecture of https://github.com/darekkay/static-marks-app/

**Comment by 12nick12** [comment]
this would be awesome, only if I was smart enough to help :-( good luck

**Comment by devnikesh** [comment]
Hi, @darekkay I gave it a try, is this the functionality which we are trying to implement. For now, just implemented for theme preference, it's gonna show up according to the user theme preference in their browser settings.
![Dark Mode](https://user-images.githubusercontent.com/63302392/149295565-c3ea0289-0cc7-45a5-875a-0f4d7fac5b55.png)

**Comment by devnikesh** [comment]
Hi, @darekkay I gave it a try. For now, just implemented for theme preference, it's gonna show up according to the user theme preference in their browser settings. Looking for your approval to continue along. :) 
![Dark Mode](https://user-images.githubusercontent.com/63302392/149295565-c3ea0289-0cc7-45a5-875a-0f4d7fac5b55.png)

**Comment by devnikesh** [comment]
Hi, @darekkay I gave it a try. For now, just implemented for theme preference, it's gonna show up according to the user theme preference in their browser settings. Looking forward to your approval to continue along. :) 
![Dark Mode](https://user-images.githubusercontent.com/63302392/149295565-c3ea0289-0cc7-45a5-875a-0f4d7fac5b55.png)

**Comment by darekkay** [comment]
Hey @devnikesh , the work in progress looks good to me :+1: I also agree that it's good to start with the browser preferences first before implementing a theme switcher later.

**Comment by devnikesh** [comment]
@darekkay , yeah sure thank you, glad you liked it.. 😄

**Comment by devnikesh** [comment]
Hey @darekkay , I'm done with the browser preference part, earlier the menu item icons and text color were not changing on dark mode, now it's fixed. Can we proceed to implement the feature ?
![Dark Mode)](https://user-images.githubusercontent.com/63302392/149386436-6777ce61-2bd4-449c-bafb-4e7723525746.png)
.

**Comment by devnikesh** [comment]
Hi @darekkay, was waiting for your approval, I've done the testing and have opened a PR. [Devnikesh/add dark mode 11](https://github.com/darekkay/static-marks-app/pull/4)

Here's a Screenshot of the test result:

![Screenshot (1352)](https://user-images.githubusercontent.com/63302392/149672359-a574ee97-d7fb-40fa-b47a-e8e2231bb0b0.png)

**Comment by darekkay** [comment]
Version [2.4.0](https://github.com/darekkay/static-marks/releases/tag/v2.4.0) published, including a Dark Mode. Thanks everyone.
