### ISSUE TITLE
Importing Bookmark Export HTML file from Raindrop.io doesn't show any URLs

### ISSUE THREAD

**Issue by nausher** [darekkay/static-marks#14]
I exported my bookmarks from raindrop.io as an HTML export.
The format used is similar to the one used by Google Bookmarks ( See sample below).

But Static marks did not pick up these bookmarks, the generated yml file is empty (also below).

**Sample record from the exported HTML file** 
```
<DT><H3 ADD_DATE="0" LAST_MODIFIED="0">Speed Dial</H3>
<DL><p>
</DL><p>
<DT><H3 ADD_DATE="0" LAST_MODIFIED="0">Unsorted</H3>
<DL><p>
<DT><A HREF="https://www.readthistwice.com/person/paul-graham" ADD_DATE="1596669210" LAST_MODIFIED="1596669220" TAGS="Read Later,books,fun,interesting">89 books Paul Graham recommended</A>
<DD>(Updated 2020) The most up to date and comprehensive list of 89 verified book recommendations from Paul Graham. Includes quotes and sources.

```

**sample_ bookmarks.yml file**
```

Imported:
  - root: []


```

This software looked quite promising as I was hoping to store my bookmarks locally/my own cloud.
But looks like I'm facing issues getting started/importing bookmarks.

**Comment by darekkay** [comment]
Hey @nausher, thanks for reporting the issue! I've fixed the problem with Raindrop imports, so please try again with `static-marks` version `2.2.2` 🙂

@all-contributors please add @nausher to maintenance
