### ISSUE TITLE
Implicit labels for links

### ISSUE THREAD

**Issue by jflip** [darekkay/static-marks#21]
A suggestion that would help users like myself that tend to remove the labels from links in bookmark bars and rely on favicons like so
![image](https://user-images.githubusercontent.com/9138082/95783550-01ea6e00-0cca-11eb-9ef6-dd384c78a2c7.png)

While this makes for a nice and clean bookmark bar it kind of messes with this project and has a result like this
![image](https://user-images.githubusercontent.com/9138082/95783638-2c3c2b80-0cca-11eb-9738-94f9ae2fa2d6.png)

My suggestion would be that when creating the .yml file, if no label exists for the link, just use the link as an 'implicit' label. 
So instead of 
 - '': 'https://play.pocketcasts.com/podcasts'

We'd have the output 
 - 'https://play.pocketcasts.com/podcasts': 'https://play.pocketcasts.com/podcasts'

Would love to give this a go if you think it is a good idea 👍

**Comment by darekkay** [comment]
Sure, great idea! I've noticed that issue when testing the import of my own bookmarks, but I didn't give it a proper thought before. Your suggestion solves it nicely :+1:

**Comment by jflip** [comment]
Awesome! Thanks 👍
