### ISSUE TITLE
Header's menu not present

### ISSUE THREAD

**Issue by Jiehong** [darekkay/static-marks#28]
Hi,

In the demo, the header has 2 div classes: a filter and a menu.

However, when using version 2.3.0, only the filter div is present, and the menu is not present at all.

No custom template is used.

Environment:

node 16, installed with yarn (`yarn add global static-marks`).

Screenshot of the issue:

![image](https://user-images.githubusercontent.com/1061229/149177036-694fd535-4aea-4e6a-bdfd-48f7d02993e0.png)

Screenshot of the demo that is correctly:

![image](https://user-images.githubusercontent.com/1061229/149177122-d7247b4a-c47b-4c3c-b30c-6cfd41fc51fe.png)

**Comment by darekkay** [comment]
Hey @Jiehong ,

this behavior is described in the documentation:

> If multiple files are provided to static-marks, they will become selectable via a menu.

The menu is there so you can switch between multiple files. If you provide only one bookmarks file, the file switcher is not required and hence not rendered:

```bash
# switcher available
$ static-marks build file1 file2

# switcher not necessary/not available
$ static-marks build file1
```

I will make the documentation more clear to prevent misunderstandings.

**Comment by Jiehong** [comment]
@darekkay : ah, I see. I thought it was linked to the collections (and in the demo, the collections and the files might be named the same, and the "All" also lead me to believe it would).

Thanks for clarifying this!

**Comment by darekkay** [comment]
Thanks, it's always good to get some feedback on the documentation! I've updated the part regarding multiple files and also changed the example collection name to differentiate it from the equal file name.
