### ISSUE TITLE
Build File Doesn't Render Properly

### ISSUE THREAD

**Issue by g33k247** [darekkay/static-marks#3]
I've installed static marks. I exported my Chrome bookmarks to an html file. I can open that file in a browser and it renders fine. 

The import to static marks works fine (no errors are thrown).

The build *.yml to *.html also appears to work fine and throws no errors.

When I open the build bookmarks.html file, it does not render properly like your demo page (except for the header).

What am I doing wrong?

![Screenshot_20190513_175446](https://user-images.githubusercontent.com/8498814/57657218-9f5ae300-75a8-11e9-8413-00ab603ae4f6.png)

**Comment by darekkay** [comment]
Hi, thanks for the report.

My guess is that your bookmarklets (ZL_HOST) are causing trouble here. I'm also using bookmarklets and I'm not able to reproduce the issue. 

Could you please remove your bookmarklets from the exported Chrome bookmarks file and try again?

If this solves the issue, can you please send me a bookmarklet from your exported Chrome bookmarks file so I can reproduce and fix the issue?

**Comment by g33k247** [comment]
Hi @darekkay as you suspected, once I removed the bookmarklets it worked just fine. I'll send you the bookmarklets.

**Comment by darekkay** [comment]
Thank you very much, I was able to reproduce the issue. Your bookmarklet includes `</script>`, which [terminates the actual script](https://stackoverflow.com/questions/28259389/how-to-put-script-in-a-javascript-string). I guess this is cross-site scripting 101, but I've missed it before.

I have fixed the issue in 46152344fe643abcf4835b3d1a8bd73634507213 and released a patched version `2.0.1`.

**Comment by g33k247** [comment]
Thank you for your help, Darek. TBH, those bookmarklets accumulated on me
and I can't remember the last time I used any of them. They are permanently
deleted! I really like your work with static marks. Simple and does one
thing really well. I've been looking for something like static marks for
quite some time now.
