### ISSUE TITLE
Github running problem

### ISSUE THREAD

**Issue by 9uest** [darekkay/static-marks#38]
Hi. I currently use github to run the project. I want to specify a template, but the template has not been effective, what is the reason?

template.html Uploaded project

Configuration:

      - name: Install and Build 🔧
        run: |
          npm install static-marks
          mkdir build
          ./node_modules/.bin/static-marks build --template-file template.html *.yml > build/index.html

**Comment by darekkay** [comment]
Hello @9uest , some questions to debug your issue:

- Does it work for you with the [example template](https://github.com/darekkay/static-marks/blob/master/docs/examples/templates/custom.html)?
- Can you provide the console log of your failed GitHub action?
- Can you provide your HTML template file?

**Comment by 9uest** [comment]
Just tested and replaced other templates and it can take effect successfully.

But using the default template, a black theme is generated on the command line, and a white theme is generated on github. What caused it?

Default template used:
https://github.com/darekkay/static-marks/blob/master/src/_template.html
