### ISSUE TITLE
How to modify the title? 

### ISSUE THREAD

**Issue by 9uest** [darekkay/static-marks#39]
Modified the template file, but it will be replaced by the default

Environment: github-page

template part code：
`<link rel="apple-touch-icon" sizes="180x180" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAj0SURBVHgB7d09bFtVGMbx97oIAVPYYHPZYGmACTqQlA0GgmBESisxIiXdIAjFXqASSE0kRlBSiRHULmWjdQYY23SBjboLZaun0qW9nDe3rhsntu/HOfY9r/8/yXGTplZlPz5+7jn3IxEf1tMFeU5WJJFT7tZ0P1l09wuSuhtwvK7LSFceyb67v+XuO3Ih6UpFiZSlIX5B1twjLLngLglQ3b67bVcJd/FAD4K8zgiMgHZdsNtFg10s0BvpJkHGlLXk66Sd95fzBfrztCkNuSzajYHp0669nGe0bkz6BfkyXZUTclMIM2ZHB9Sb8kW6MukXxwdaK0bqugwVA7O34PrE5YNMjjG6cmT/sCVA/Yzs1ccHWof25KAzA/WUyln5Jrk0/OOjgdYNQO3M1AzUW89tKL4+vKF4tEM35DphRgQWHs+8HXI40FlvbgoQh0WX2dbTPxhUjmyu+bYAcenJfTkpW0lPvxmM0A3ZFCA+uivGev+bbIRmdEbcnozS2QjdYG85RO3JKJ0FOpE1AWKWyjt6l1A3YMZ9ebFB3YAZL8iKVg72ooMNj2SxcXAcIGBDs+HKdFMACxpySitHUwAbFiYfsQLEg0DDFgINUwg0TCHQMOUZgSy+nN0Wnstusek9EOnec7eeyP5dmWtzGWgN7dk3RD54bRBkSzq3RS7dyO416PMkkY00lTmxdFJk893sfl7sumC3r81PsOci0M0XRXY+mq8gD5uXYJvfKFw7LXLzs/kOs9KKpc/D+mkxzXSgL74vsvWevY5clj4PF9/LnherTFYOfeEuf8KoPI7Ohiz/kM2QWGJyhN75mDBPorM7+qa3xlyg9eN05VVBDvqmt1Y/TAVaN3zW3xYUoM+XpQHATKB1ak7nmFGcVjQrG85mAr15xoWaU0yWomG28slmItA6OmvdQHk6X29hlDYRaB2dUY2VUdpEoJdeEXiwZmAVMfpA69QT3dkPHaVjn7+PPtC6QAB/Yn8+ow/0O6wIehV7fYs+0DrDAX9OvSRRI9A4ZOF5iVr0gWbXUL9ifz456humEGiYQqBhCoGGKQQapnDmpAr0lADLP/o9NUDrDPt1V8EIXcH5q/7Pc9G6Zu/A1Wki0BV0AlwML9bz69UFgS5JTwMQYiRdeU1QAYEu6U5PgviAI9YrIdAldf4W77RqMEJXQ6BLCnEeZsJcHYEuKcQGIXWjOgJdQogwK46NrI5Al3DrH/FOz17EdF11BLqEIHWD/uwFgS5h/1/xjg1CPwh0QQdXm/K83E3d8IdAF3QrwOhM3fCHQBcUYkGFuuEPgS7I94IKdcMvAl2Q7xkO6oZfBLqAENN1LKb4RaAL8L2gwokm/SPQBfgeoVc5Sbt3BLqArud9oKkb/hHonPToFJ8zHNSNMDjqOyff03X6eCe/k9J0qk+PDueajIcR6Jz2PC+o6Ihf9ZjEcz+7QH8leAqVI6dQ+0BXEfupb0Mg0DmFOOSqKq7+dRSBziHUKQuq0Osycm3Gowh0DnUbnbkM9GgEOoe9mvVnLgM9GoHOoU4jtM5fUzVGI9AT+F5QqULnnnc+FoxBoCeo0+isvZmqMR6BnmAvwBEqZWjVsHBx+dAI9AR1WVChauRDoCeoQ+WgauRHoGtO55xbrAjmxs5JE+hHffu34iuFvf/8rC5e/1RQAIGeQHfPLLOLpr4J9HopVVA1iqNy1BRVoxwCXVNUjXIIdA1RNcoj0DVD1aiGQNcMVaMaAl0jVI3qCHRNUDX8INA1QdXwg0DXAFXDHwI9Y1QNvwj0jO18JPCIQM/Q2ulsx334Q6BnhKoRBoGekYvvc22VEAj0DOhpCDhraBgEeso461FYBHrKOOtRWAR6ijjBYngEekqoGtNBoAMZnsGgakwHgQ5k9c3BTIaOzFSN6eCo70B0hL78iWDKGKFhCoGGKQQaphBomEKgYQqBhikEGqYQaJhCoGEKgYYpBBqmEGiYQqBhCoGGKQQaphBomEKgYQqBhikEegq6PZHO7eweYXFMYUDdeyLnfsnC3KcHy3KC83AYoQPQa3zrpZFPfnc4zGr3hvv5tyLnrzJih0CgPdv+PQvspOt8b/0hsvyDyKUbAo8ItCc6EmtA13/NRug8tJKc/SUbyffvCjwg0BVpKD/8KQvzcL0o8hivf5/1bWpINQS6pH5P1iBe+Uu86PdrfVyUQ6BL0ABrkLUn560XRejjag2hXxdHoAvo92StGFoTQur3a33jUEPyI9A56Cis02xVenJZurGoNYR+nQ8LKxNon9UpthDVogjt1/pmWn8ruxwcjscIPYKGR3tsqJ5chtYQnRakX49GoIdoaLRa6C10Ty6r36+pIUdFH2hfo+e45eq6CrGMXpdPo7KiD7SPFba8y9V15XMZPfYVy+gDXeVFLLNcXVe+ltFj7+aJbKSpRO76p8UuAq8vvn5M+1rhq6Myu6nqG0HnvWNmItB6yTQN9aQXT0dhrRd1mIabltaZfJeTO9gY/rG+G8J5mQi00ov06Is3ao5WN6Da1+J/wcrQN7w+N6vHXInL2pvcTKD7NNhaPxZfzr7Xrf8rf87PiDyOBnvxJdvPjblAY76xsAJTCDRMIdAwhUDDlIbbLGT3FpjRkJRAw4yuVo59ASxIskDfEcCCh3KLERqW7DfkWbkigA2dhrSSntsw7AgQs9Q1jQtJN5uHTmRPgJilsq13WaCflS3moxG5jn7JAp3Vjm0B4rSrdUP/MFj6ZpRGrB5Ju//HQaAZpRGndn90VsmRv95Ib7qviwLUXSpd+SY5dHj00b3tHsmHVA9EQBvF8vAPjwZah++Hcl6AOkvl3NNVo+/4/aEvJLsig6IN1EzbVY1jV7iTsf9sI225r5sC1Edbvk5ao/5yfKDVF+mKG8d33BDPpSIxS7pdd96FeXfcL00OtPo8bbrfvO5uTQGmb/9gsuKYzjwsX6D7qCCYLh2Vt8dVjGHFAq2y0brlbqsChJEF+b5bvd5KCk0hFw90nwZbZElOyJrr1yzEoLpEOi5Le2WCPHgIH/rh1hXGE3LK/af0+6YAx+s9vmk3vnNw/0CulA3x0/4H/Jp4ICk5CmMAAAAASUVORK5CYII=">
	
    <script>var injected="%INJECTED%"</script>
    <title>Bookmarks</title>
    <script>(function() {
      document.documentElement.dataset.theme = localStorage.getItem("theme")
        || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "default");
    })();</script>
    <script type="module" crossorigin>var Mc=Object.defineProperty,Oc=Object.defineProperties;var Fc=Object.getOwnPropertyDescriptors;var ir=Object.getOwnPropertySymbols;var Zi=Object.prototype.hasOwnProperty,bi=Object.prototype.propertyIsEnumerable;var Ji=(e,t,n)=>t in e?Mc(e,t,{enumerable:!0,configurable:!0,writable:!0,value:n}):e[t]=n,Rt=(e,t)=>{for(var n in t||(t={}))Zi.call(t,n)&&Ji(e,n,t[n]);if(ir)for(var n of ir(t))bi.call(t,n)&&Ji(e,n,t[n]);return e},Ml=(e,t)=>Oc(e,Fc(t));var Ol=(e,t)=>{var n={};for(var r in e)Zi.call(e,r)&&t.indexOf(r)<0&&(n[r]=e[r]);if(e!=null&&ir)for(var r of ir(e))t.indexOf(r)<0&&bi.call(e,r)&&(n[r]=e[r]);return n};window.regeneratorRuntime=void 0;const Ic=function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const l of document.querySelectorAll('link[rel="modulepreload"]'))r(l);new MutationObserver(l=>{for(const o of l)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(l){const o={};return l.integrity&&(o.integrity=l.integrity),l.referrerpolicy&&(o.referrerPolicy=l.referrerpolicy),l.crossorigin==="use-credentials"?o.credentials="include":l.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(l){if(l.ep)return;l.ep=!0;const o=n(l);fetch(l.href,o)}};Ic();var R={exports:{}},M={};/**
`

**Comment by darekkay** [comment]
You can pass the title to the `build` command:

```
static-marks build --title Bookmarks ...
```

**Comment by 9uest** [comment]
> --title Bookmarks

problem solved
thanks
