### ISSUE TITLE
Does it support adaptation?

### ISSUE THREAD

**Issue by 9uest** [darekkay/static-marks#40]
Hello
Does the height of each group support self-adaptation?

**Comment by darekkay** [comment]
If you mean a "masonry layout", the answer is "no".

**Comment by darekkay** [comment]
Based on the non-existent [browser support](https://caniuse.com/mdn-css_properties_grid-template-rows_masonry) and potential [accessibility issues](https://www.matuzo.at/blog/2023/100daysof-day71/), for now a masonry layout is not an option for this project.
