### ISSUE TITLE
Error unclear if column is forgotten

### ISSUE THREAD

**Issue by Jiehong** [darekkay/static-marks#47]
## Issue

When running static mark, the following error occurs:

```
static-marks build --title 'Personal Bookmarks' ./bookmarks.yml > ./html/index.html
× Could not convert YAML file: /Users/username/dev/personal-static-files/bookmarks.yml
  bucket[bucketName].map is not a function
× Process aborted: at least one YAML file is malformed.
```

This happens because I forgot 1 level, and can be reproduced with the following yml file:

```
Section:
  - test: http://github.com
```

The problem is that it's expecting a level in between to name the column, but I didn't realise, and I thought the error must be coming from characters to to escape in the url or to quote something to make it a valid yaml.

The fix is simple, but unrelated to the yaml being mal formatted:

```
Section:
  - Column:
    - test: http://github.com
```

## Expected behaviour

The error message should be more accurate, as in this case the yaml file is not malformed, but its structure is not the one expected, and the message `bucket[bucketName].map is not a function` is meaningless to the user.

Instead, it should be detected that a level is missing, or something, and tell the user about it, maybe with an example.

**Comment by darekkay** [comment]
Thank you for the suggestion! 503a4d2e4d360791e6a1b537a219f06a3d240deb improves the error messages.
