### ISSUE TITLE
Nested hierarchy levels?

### ISSUE THREAD

**Issue by thle** [darekkay/static-marks#5]
I try to understand the YAML syntax. In your demo ur'e using nested Links inside a sub-menu (Icons->Font Awesome). Can you provide the YAML syntax or the source for that?
Regards

**Comment by thle** [comment]
Nevermind, I just found it in the docs...

**Comment by darekkay** [comment]
@thle Do you have some suggestions on how to improve the YAML syntax documentation? Was it hard to understand? I know it's not straightforward, because of the limitations of YAML and my wish of supporting a concise syntax for bookmarks with and without notes.
