### ISSUE TITLE
Non-minified version of default template

### ISSUE THREAD

**Issue by k-kalinowski** [darekkay/static-marks#6]
Hi, 

is it possible to provide non-minified version of the default page template provided with static-marks? I'd like to add autofocus to the search input and the current minified version doesn't lend itself to such modifications ;)

**Comment by darekkay** [comment]
Hey,

I've just published the code for the template [here](https://github.com/darekkay/static-marks-app). The documentation is practically non-existent, but I hope the code and the structure is easy to follow. Let me know if you have any issues. All PRs are highly welcome, of course 😄
