### ISSUE TITLE
Autofocus search field

### ISSUE THREAD

**Issue by darekkay** [darekkay/static-marks#7]
It would be nice to have the search field autofocused
- on page load
- after pressing the `X` button to clear the search input

This use case was also described in #6.

As this affects the UI, the implementation has to be done in [darekkay/static-marks-app](https://github.com/darekkay/static-marks-app/).

**Comment by veerreshr** [comment]
Could I work on this issue @darekkay ?

**Comment by darekkay** [comment]
@veerreshr Sure 🚀

**Comment by darekkay** [comment]
Thanks! 

@all-contributors please add @veerreshr to maintenance

**Comment by darekkay** [comment]
Released in version [2.2.1](https://github.com/darekkay/static-marks/releases/tag/v2.2.1).
