### ISSUE TITLE
List duplicate links in the report

### ISSUE THREAD

**Issue by darekkay** [darekkay/static-marks#8]
The [report](https://github.com/darekkay/static-marks/blob/master/bin/report/index.js) command introduced in `2.1.0` returns the total number of links. This command should be improved to also find and list all duplicate links. There might be valid use cases for having duplicate links, so there should be a flag to disable this feature within `report` command (e.g. `--no-duplicates`).

**Comment by jflip** [comment]
Hey @darekkay mind if I give this a go? Still fairly fresh to open source but would like to support if I can

**Comment by darekkay** [comment]
Hey John, sure! Let me know if there's any support you require to get started 🚀
